# Generated by Django 5.0.1 on 2024-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_lesson_course_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(verbose_name='сумма оплаты'),
        ),
    ]
