# Generated by Django 5.0.1 on 2024-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_payments_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
    ]
