# Generated by Django 5.0.1 on 2024-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_payments_is_paid_payments_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.CharField(default='RUB', max_length=10, verbose_name='валюта'),
        ),
    ]
