# Generated by Django 5.0.1 on 2024-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_payments_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.TextField(blank=True, null=True, verbose_name='id сессии'),
        ),
    ]
