# Generated by Django 5.0.1 on 2024-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_payments_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_description',
            field=models.TextField(default='New interesting description of the Course.', verbose_name='description number two'),
        ),
    ]
